### ISSUE TITLE
How to add response headers to a Angular application which is hosted in Azure Linux App service 

### ISSUE THREAD

**Issue by aadityaparcha1** [Ajsalemo/custom-response-header-examples#1]
How to add response headers to a Angular application which is hosted in Azure Linux App service.

**Comment by Ajsalemo** [comment]
@aadityaparcha1 - If this is a typical Angular application, aka client-side JavaScript only, then you will need to use something like Application Gateway or a custom Docker Image using NGINX, Apache, etc. serving your production Angular build to do this for you.

This is the same approach for pretty much all SPA's.

Client-side code has no awareness of how to set response headers, because it's client-side executed, and the Node offering for App Service Linux only comes with Pm2 - which is just a process manager, and can't do this. Windows App Service can at least use a web.config to do this (since this is server executed), but obviously this doesn't work on Linux.

You could possibly use a PHP Blessed Image as what's described here - https://azureossd.github.io/2022/05/25/Editing-Response-Headers-on-Linux-App-Service/index.html#azure-application-gateway - however for simplicity, it's highly recommended to just use either an App Gateway or Custom Docker Image to do this yourself.

**Comment by Ajsalemo** [comment]
Closing as suggestions/resolutions were provided.
